<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ELOA - Empresas Cadastradas</title>
    <link rel="stylesheet" href="../CSS/parceria.css">
</head>
<body>
    <!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ELOA</title>
    <link rel="stylesheet" href="/NAVEGACAO_WEB/menu.css">
   
</head>
<body>
    <!-- Overlay -->
    <div class="overlay" id="overlay"></div>

    <!-- Aqui vai carregar o nav -->
    <div id="sidebar-container"></div> 

    <div class="main-content-full">
        <div class="filters">
            <h3>Filtros:</h3>
            <div class="filter-row">
                <select class="filter-select" id="locationFilter">
                    <option value="">Localização</option>
                    <option value="sao-paulo">São Paulo</option>
                    <option value="rio-janeiro">Rio de Janeiro</option>
                    <option value="belo-horizonte">Belo Horizonte</option>
                    <option value="brasilia">Brasília</option>
                </select>
                <select class="filter-select" id="areaFilter">
                    <option value="">Área de atuação</option>
                    <option value="tecnologia">Tecnologia</option>
                    <option value="marketing">Marketing</option>
                    <option value="consultoria">Consultoria</option>
                    <option value="financeiro">Financeiro</option>
                </select>
                <button class="apply-filters" onclick="applyFilters()">Aplicar Filtros</button>
            </div>
        </div>

        <h2 class="section-title">Empresas Cadastradas</h2>

        <div class="companies-grid" id="companiesGrid">
            <!-- Companies will be generated by JavaScript -->
        </div>
    </div>

    <script src="../JS/parceria.js"></script>
</body>
</html>
